name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: dbecommercefinal

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build with Maven
        run: ./mvnw clean install

      - name: Start Spring Boot application
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/dbecommercefinal?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root
        run: ./mvnw spring-boot:run
